name: my_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  freezed: ^2.5.2
  freezed_annotation: ^2.4.1
  flip_card: ^0.7.0
  oktoast: ^3.4.0
  flutter_riverpod: ^2.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.9
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  assets:
    - json/
    - images/
    - images/card_logo/
  fonts:
    - family: OCR-A
      fonts:
        - asset: fonts/OCR-A.ttf
    - family: OCR-B
      fonts:
        - asset: fonts/OCR-B.ttf
    - family: Farrington-7B
      fonts:
        - asset: fonts/Farrington-7B.ttf